### ISSUE TITLE
Reshape cannot infer the missing input size 

### ISSUE THREAD

**Issue by keshav99** [vudung45/FaceRec#17]
Hi I'm getting this error when trying to save by pressing q

Traceback (most recent call last):
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1330, in _do_call
    return fn(*args)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1315, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1423, in _call_tf_sessionrun
    status, run_metadata)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: InceptionResnetV1/Logits/Flatten/flatten/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](InceptionResnetV1/Logits/AvgPool_1a_8x8/AvgPool-0-0-TransposeNCHWToNHWC-LayoutOptimizer, InceptionResnetV1/Logits/Flatten/flatten/Reshape/shape)]]
         [[Node: l2_normalize/_987 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2219_l2_normalize", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 157, in <module>
    main(args);
  File "main.py", line 28, in main
    create_manual_data();
  File "main.py", line 140, in create_manual_data
    person_features[pos] = [np.mean(extract_feature.get_features(person_imgs[pos]),axis=0).tolist()]
  File "D:\desktop\facerec\face_feature.py", line 31, in get_features
    return self.sess.run(self.embeddings, feed_dict = {self.x : images})
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 908, in run
    run_metadata_ptr)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1143, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1324, in _do_run
    run_metadata)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1343, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: InceptionResnetV1/Logits/Flatten/flatten/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](InceptionResnetV1/Logits/AvgPool_1a_8x8/AvgPool-0-0-TransposeNCHWToNHWC-LayoutOptimizer, InceptionResnetV1/Logits/Flatten/flatten/Reshape/shape)]]
         [[Node: l2_normalize/_987 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2219_l2_normalize", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'InceptionResnetV1/Logits/Flatten/flatten/Reshape', defined at:
  File "main.py", line 155, in <module>
    extract_feature = FaceFeature(FRGraph)
  File "D:\desktop\facerec\face_feature.py", line 22, in __init__
    resnet.inference(self.x, 0.6, phase_train=False)[0], 1, 1e-10); #some magic numbers that u dont have to care about
  File "D:\desktop\facerec\architecture\inception_resnet_v1.py", line 155, in inference
    reuse=reuse)
  File "D:\desktop\facerec\architecture\inception_resnet_v1.py", line 236, in inception_resnet_v1
    net = slim.flatten(net)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1490, in flatten
    outputs = core_layers.flatten(inputs)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\layers\core.py", line 415, in flatten
    return layer.apply(inputs)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\layers\base.py", line 825, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\layers\base.py", line 714, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\layers\core.py", line 376, in call
    outputs = array_ops.reshape(inputs, (array_ops.shape(inputs)[0], -1))
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6978, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3309, in create_op
    op_def=op_def)
  File "C:\Users\keshh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1669, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: InceptionResnetV1/Logits/Flatten/flatten/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](InceptionResnetV1/Logits/AvgPool_1a_8x8/AvgPool-0-0-TransposeNCHWToNHWC-LayoutOptimizer, InceptionResnetV1/Logits/Flatten/flatten/Reshape/shape)]]
         [[Node: l2_normalize/_987 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2219_l2_normalize", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by ahmad53135** [comment]
maybe because of low gpu memory

**Comment by DanqingZ** [comment]
Did you solve this problem?

**Comment by ahmad53135** [comment]
in this error, there is a sentence that says "for an empty tensor unless all specified input sizes are non-zero". So, I checked my input to see if it's empty or not before reshaping and in that way, it is solved.
