### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by mashrin** [vudung45/FaceRec#3]
Kindly help! I followed all the mentioned instruction. On running the code, I am getting this:

Loading model...
Model loaded
Loading MTCNN Face detection model
MTCNN Model loaded
[INFO] camera sensor warming up...
Traceback (most recent call last):
  File "main.py", line 151, in <module>
    main(args);
  File "main.py", line 26, in main
    camera_recog()
  File "main.py", line 47, in camera_recog
    rects, landmarks = face_detect.detect_face(frame,80);#min face size is set to 80x80
  File "/home/intel-i2r/Documents/FaceRec-master/mtcnn_detect.py", line 54, in detect_face
    img = cv2.resize(img,(int(len(img[0])/self.scale_factor), int(len(img)/self.scale_factor)))
TypeError: 'NoneType' object is not subscriptable

**Comment by vudung45** [comment]
Hi @mashrin 
I'm not sure if this is your issue but try to install tensorflow 1.1.0-rc0 (1.2.0 should work as well)
Other than that, please try to add some print around those lines to debug, and also check if your opencv (cv2) was installed successfully.

**Comment by mashrin** [comment]
I'll do that. Btw, the readme mentions the installation of cv3.

Anyway, I will try a few things out and will provide an update regarding
the same.

Thanks for your time!

**Comment by mashrin** [comment]
Uninstalled latest tensorflow to 1.1.0rc0. Also, cv2 is properly installed, tested it with some basic example codes (including the use of the webcam) but I am still getting the same error. Kindly see if you can help me with this.

Thanks!

**Comment by vudung45** [comment]
@marshrin: Could you try to print(img) out before that 54th line in mtcnn_detect. I think there is something wrong with your input img

**Comment by mashrin** [comment]
Hey,
Sorry for the delayed reply. Wish you a happy new year.

I tried playing around with this. The issue seemed to be with OpenCV as we expected it. After reinstalling it, it is now resolved.

Two things that I have come across further are-
1. While using input mode, to save a new face, after pressing 'q' to save and add the face, the frame hangs.
System configuration is: 6th gen i7, 16GB RAM, 4 GB GTX960M

2. While running the application, after some time (close to 30 seconds), I am getting this error and the application turns off. This seems to be an issue. Kindly provide your suggestions for this.

`Loading model...
Model loaded
Loading MTCNN Face detection model
MTCNN Model loaded
[INFO] camera sensor warming up...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[Node: InceptionResnetV1/Logits/Flatten/flatten/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](InceptionResnetV1/Logits/AvgPool_1a_8x8/AvgPool, InceptionResnetV1/Logits/Flatten/flatten/Reshape/shape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 151, in <module>
    main(args);
  File "main.py", line 26, in main
    camera_recog()
  File "main.py", line 54, in camera_recog
    features_arr = extract_feature.get_features(aligns)
  File "/home/mashrin/Documents/FaceRec-master/face_feature.py", line 31, in get_features
    return self.sess.run(self.embeddings, feed_dict = {self.x : images})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[Node: InceptionResnetV1/Logits/Flatten/flatten/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](InceptionResnetV1/Logits/AvgPool_1a_8x8/AvgPool, InceptionResnetV1/Logits/Flatten/flatten/Reshape/shape)]]

Caused by op 'InceptionResnetV1/Logits/Flatten/flatten/Reshape', defined at:
  File "main.py", line 149, in <module>
    extract_feature = FaceFeature(FRGraph)
  File "/home/mashrin/Documents/FaceRec-master/face_feature.py", line 22, in __init__
    resnet.inference(self.x, 0.6, phase_train=False)[0], 1, 1e-10); #some magic numbers that u dont have to care about
  File "/home/mashrin/Documents/FaceRec-master/architecture/inception_resnet_v1.py", line 155, in inference
    reuse=reuse)
  File "/home/mashrin/Documents/FaceRec-master/architecture/inception_resnet_v1.py", line 236, in inception_resnet_v1
    net = slim.flatten(net)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1434, in flatten
    outputs = core_layers.flatten(inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/core.py", line 400, in flatten
    return layer.apply(inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 671, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/core.py", line 362, in call
    outputs = array_ops.reshape(inputs, (array_ops.shape(inputs)[0], -1))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3938, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[Node: InceptionResnetV1/Logits/Flatten/flatten/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](InceptionResnetV1/Logits/AvgPool_1a_8x8/AvgPool, InceptionResnetV1/Logits/Flatten/flatten/Reshape/shape)]]
`

Thanks!

**Comment by vudung45** [comment]
@mashrin it's very likely that the input image is null. This is probably a mistake on my end since, as stated, I didn't handle a lot of camera error exceptions in the main.py file. Please take a lot at your input camera image, it's probably NoneType at some point during the run, wrap a big try catch around the code to avoid it from getting random crashes due to unexpected input.

**Comment by rashmisgh** [comment]
@vudung45  what do you mean by "wrap a big try catch around the code to avoid it from getting random crashes" as i am also getting same issue, in fact i have added "input" through webcam . but after running the main.py file the camera run for approx  20sec and it get closed.
another thing i would like to know that the image we are giving in new input to the database by pressing "q" where is the clicked image going??
