### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 1 with size 1

### ISSUE THREAD

**Issue by AlvaroN1997** [vudung45/FaceRec#35]
I got this error when i put `python main.py --mode "input"`. How do i solve this?

```
Traceback (most recent call last):
  File "main.py", line 160, in <module>
    main(args);
  File "main.py", line 28, in main
    camera_recog()
  File "main.py", line 53, in camera_recog
    aligned_face, face_pos = aligner.align(160,frame,landmarks[:,i])
IndexError: index 1 is out of bounds for axis 1 with size 1
```

**Comment by Firdauzfan** [comment]
Just use this command python main.py --mode input 
If you use "input", it will out of index in args.

**Comment by vudung45** [comment]
8caa97e  fixed it
