### ISSUE TITLE
Unable to locate 20170512-110547.pb

### ISSUE THREAD

**Issue by sierra1bravo** [vudung45/FaceRec#38]
Hi

I do not see this file in the zip file in the link provided...consequently, main.py does not run.

Thanks for any help.

**Comment by vudung45** [comment]
@sierra1bravo  please redownload the model. I've updated it!

**Comment by sierra1bravo** [comment]
Thanks, will do! I hope it is available at the same link as mentioned in
the documentation.


s1b

**Comment by cluzier** [comment]
> I am getting the same error, that file is not in the models folder, but rather these:
> 
> ```
> 
> model-20170512-110547.ckpt-250000.index
> 
> model-20170512-110547.ckpt-250000.data-00000-of-00001
> ```
> 
> I renamed the second one to the file which is seeked, but even after then I got:
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 161, in <module>
>     extract_feature = FaceFeature(FRGraph)
>   File "/home/user/workspace/FaceRec/face_feature.py", line 22, in __init__
>     self.__load_model(model_path)
>   File "/home/user/workspace/FaceRec/face_feature.py", line 49, in __load_model
>     graph_def.ParseFromString(file_.read())
> google.protobuf.message.DecodeError: Error parsing message
> ```

I see no .pb file either so I am also unsure which file to use.

**Comment by hwhh** [comment]
Hi, 

How did you solve this?
